/* Built-in content catalogs: transitions, clip filters, backgrounds, audio effects, EQ presets */
(function (IM) {
  'use strict';
  function catalog(list) {
    const map = new Map(list.map((x) => [x.id, x]));
    return { list, get: (id) => map.get(id), has: (id) => map.has(id) };
  }

  IM.Transitions = catalog([
    { id: 'cross-dissolve', name: 'Cross Dissolve' },
    { id: 'cross-blur', name: 'Cross Blur' },
    { id: 'fade-black', name: 'Fade to Black' },
    { id: 'fade-white', name: 'Fade to White' },
    { id: 'spin-in', name: 'Spin In' },
    { id: 'spin-out', name: 'Spin Out' },
    { id: 'circle-open', name: 'Circle Open' },
    { id: 'circle-close', name: 'Circle Close' },
    { id: 'doorway', name: 'Doorway' },
    { id: 'swap', name: 'Swap' },
    { id: 'cube', name: 'Cube' },
    { id: 'mosaic', name: 'Mosaic' },
    { id: 'wipe-left', name: 'Wipe Left' },
    { id: 'wipe-right', name: 'Wipe Right' },
    { id: 'wipe-up', name: 'Wipe Up' },
    { id: 'wipe-down', name: 'Wipe Down' },
    { id: 'slide-left', name: 'Slide Left' },
    { id: 'slide-right', name: 'Slide Right' },
    { id: 'puzzle-left', name: 'Puzzle Left' },
    { id: 'puzzle-right', name: 'Puzzle Right' },
    { id: 'page-curl-left', name: 'Page Curl Left' },
    { id: 'page-curl-right', name: 'Page Curl Right' },
    { id: 'cross-zoom', name: 'Cross Zoom' },
    { id: 'ripple', name: 'Ripple' },
  ]);

  IM.Filters = catalog([
    { id: 'none', name: 'None' },
    { id: 'vivid', name: 'Vivid' },
    { id: 'vivid-warm', name: 'Vivid Warm' },
    { id: 'vivid-cool', name: 'Vivid Cool' },
    { id: 'dramatic', name: 'Dramatic' },
    { id: 'dramatic-warm', name: 'Dramatic Warm' },
    { id: 'dramatic-cool', name: 'Dramatic Cool' },
    { id: 'mono', name: 'Mono' },
    { id: 'silvertone', name: 'Silvertone' },
    { id: 'noir', name: 'Noir' },
    { id: 'comic', name: 'Comic' },
    { id: 'comic-mono', name: 'Comic Mono' },
    { id: 'comic-sepia', name: 'Comic Sepia' },
    { id: 'cartoon', name: 'Cartoon' },
    { id: 'blockbuster', name: 'Blockbuster' },
    { id: 'dreamy', name: 'Dreamy' },
    { id: 'sci-fi', name: 'Sci-Fi' },
    { id: 'romantic', name: 'Romantic' },
    { id: 'flashback', name: 'Flashback' },
    { id: 'old-world', name: 'Old World' },
    { id: 'western', name: 'Western' },
    { id: 'aged-film', name: 'Aged Film' },
    { id: 'silent-era', name: 'Silent Era' },
    { id: '50s-tv', name: '50s TV' },
    { id: 'film-grain', name: 'Film Grain' },
    { id: 'black-white', name: 'Black & White' },
    { id: 'sepia', name: 'Sepia' },
    { id: 'bleach-bypass', name: 'Bleach Bypass' },
    { id: 'bright', name: 'Bright' },
    { id: 'glow', name: 'Glow' },
    { id: 'vignette', name: 'Vignette' },
    { id: 'duotone', name: 'Duotone' },
    { id: 'camo', name: 'Camo' },
    { id: 'heat-wave', name: 'Heat Wave' },
    { id: 'x-ray', name: 'X-Ray' },
    { id: 'negative', name: 'Negative' },
    { id: 'raster', name: 'Raster' },
    { id: 'flipped', name: 'Flipped' },
  ]);

  // kind = shader background kind; editable: colors can be changed in the viewer
  IM.Backgrounds = catalog([
    { id: 'black', name: 'Black', kind: 'solid', color1: '#000000', color2: '#000000', editable: 1 },
    { id: 'white', name: 'White', kind: 'solid', color1: '#ffffff', color2: '#ffffff', editable: 1 },
    { id: 'grey', name: 'Grey', kind: 'solid', color1: '#6e6e70', color2: '#6e6e70', editable: 1 },
    { id: 'blue', name: 'Blue', kind: 'solid', color1: '#1b4f9c', color2: '#1b4f9c', editable: 1 },
    { id: 'gradient-black', name: 'Gradient - Black', kind: 'gradient-radial', color1: '#3a3a3c', color2: '#000000', editable: 2 },
    { id: 'gradient-white', name: 'Gradient - White', kind: 'gradient-radial', color1: '#ffffff', color2: '#b8bcc4', editable: 2 },
    { id: 'gradient-blue', name: 'Gradient - Blue', kind: 'gradient', color1: '#4f9be8', color2: '#0d2a5c', editable: 2 },
    { id: 'clouds', name: 'Clouds', kind: 'clouds', animated: true },
    { id: 'underwater', name: 'Underwater', kind: 'underwater', animated: true },
    { id: 'aurora', name: 'Aurora', kind: 'aurora', animated: true },
    { id: 'stars', name: 'Starfield', kind: 'stars', animated: true },
    { id: 'bokeh', name: 'Bokeh', kind: 'bokeh', color1: '#1c2a4a', color2: '#050508', animated: true, editable: 2 },
    { id: 'pastel', name: 'Pastel', kind: 'pastel', animated: true },
    { id: 'organic', name: 'Organic', kind: 'organic', color1: '#c86b2c', color2: '#f2c14e', editable: 2 },
    { id: 'paper', name: 'Paper', kind: 'paper' },
    { id: 'formal', name: 'Formal', kind: 'formal', color1: '#3c0a12', color2: '#c9a24a', editable: 2 },
    { id: 'blueprint', name: 'Blueprint', kind: 'blueprint' },
    { id: 'pinstripes', name: 'Pinstripes', kind: 'pinstripes', color1: '#2a2d36', color2: '#2a2d36', editable: 1 },
    { id: 'stripes', name: 'Stripes', kind: 'stripes', color1: '#f25c54', color2: '#f7b267', editable: 2 },
    { id: 'curtain', name: 'Curtain', kind: 'curtain' },
    { id: 'chalkboard', name: 'Chalkboard', kind: 'chalkboard' },
    { id: 'watercolor', name: 'Watercolor', kind: 'watercolor', color1: '#6fa8dc', color2: '#e69ab8', editable: 2 },
    { id: 'sunset', name: 'Sunset', kind: 'sunset' },
    { id: 'tiles', name: 'Tiles', kind: 'tiles', color1: '#3f7cac', color2: '#95afba', editable: 2 },
    { id: 'wood', name: 'Wood', kind: 'wood' },
  ]);

  IM.AudioEffects = catalog([
    { id: 'none', name: 'None' },
    { id: 'cosmic', name: 'Cosmic' },
    { id: 'robot', name: 'Robot' },
    { id: 'echo', name: 'Echo' },
    { id: 'large-room', name: 'Large Room' },
    { id: 'cathedral', name: 'Cathedral' },
    { id: 'telephone', name: 'Telephone' },
    { id: 'muffled', name: 'Muffled' },
    { id: 'shortwave', name: 'Shortwave Radio' },
    { id: 'alien', name: 'Alien' },
    { id: 'chipmunk', name: 'Chipmunk' },
    { id: 'pitch-down', name: 'Pitch Down' },
  ]);

  IM.EQPresets = catalog([
    { id: 'flat', name: 'Flat', bands: [0, 0, 0, 0, 0] },
    { id: 'voice', name: 'Voice Enhance', bands: [-4, -1, 3, 4, 1] },
    { id: 'music', name: 'Music Enhance', bands: [3, 1, 0, 1, 3] },
    { id: 'loudness', name: 'Loudness', bands: [6, 2, 0, 2, 5] },
    { id: 'hum', name: 'Hum Reduction', bands: [-18, 0, 0, 0, 0], hum: true },
    { id: 'bass-boost', name: 'Bass Boost', bands: [8, 4, 0, 0, 0] },
    { id: 'bass-reduce', name: 'Bass Reduce', bands: [-10, -5, 0, 0, 0] },
    { id: 'treble-boost', name: 'Treble Boost', bands: [0, 0, 0, 4, 8] },
    { id: 'treble-reduce', name: 'Treble Reduce', bands: [0, 0, 0, -5, -10] },
  ]);
  IM.EQ_FREQS = [80, 300, 1200, 4000, 10000];

  IM.FONTS = [
    'Helvetica Neue', 'Helvetica', 'Avenir Next', 'Futura', 'Gill Sans', 'Optima', 'Didot', 'Baskerville', 'Georgia',
    'Times New Roman', 'Palatino', 'Hoefler Text', 'American Typewriter', 'Courier', 'Menlo', 'Chalkboard', 'Marker Felt',
    'Noteworthy', 'Copperplate', 'Snell Roundhand', 'Bradley Hand', 'Zapfino', 'Impact', 'Arial Black', 'Trebuchet MS', 'Verdana', 'Papyrus',
  ];
  const FONT_STACKS = {
    'Helvetica Neue': '"Helvetica Neue", Helvetica, Arial, sans-serif',
    'Helvetica': 'Helvetica, "Helvetica Neue", Arial, sans-serif',
    'Avenir Next': '"Avenir Next", Avenir, "Segoe UI", "Helvetica Neue", sans-serif',
    'Futura': 'Futura, "Century Gothic", "Trebuchet MS", "Avenir Next", sans-serif',
    'Gill Sans': '"Gill Sans", "Gill Sans MT", Calibri, "Trebuchet MS", sans-serif',
    'Optima': 'Optima, Candara, "Segoe UI", sans-serif',
    'Didot': 'Didot, "Bodoni 72", "Bodoni MT", "Times New Roman", serif',
    'Baskerville': 'Baskerville, "Baskerville Old Face", "Libre Baskerville", Georgia, serif',
    'Georgia': 'Georgia, "Times New Roman", serif',
    'Times New Roman': '"Times New Roman", Times, serif',
    'Palatino': 'Palatino, "Palatino Linotype", "Book Antiqua", Georgia, serif',
    'Hoefler Text': '"Hoefler Text", Garamond, Georgia, serif',
    'American Typewriter': '"American Typewriter", "Courier New", Courier, monospace',
    'Courier': 'Courier, "Courier New", monospace',
    'Menlo': 'Menlo, Monaco, Consolas, monospace',
    'Chalkboard': 'Chalkboard, "Chalkboard SE", "Comic Sans MS", cursive',
    'Marker Felt': '"Marker Felt", "Comic Sans MS", cursive',
    'Noteworthy': 'Noteworthy, "Comic Sans MS", cursive',
    'Copperplate': 'Copperplate, "Copperplate Gothic Light", "Trebuchet MS", serif',
    'Snell Roundhand': '"Snell Roundhand", "Brush Script MT", cursive',
    'Bradley Hand': '"Bradley Hand", "Segoe Print", cursive',
    'Zapfino': 'Zapfino, "Snell Roundhand", "Brush Script MT", cursive',
    'Impact': 'Impact, "Arial Black", sans-serif',
    'Arial Black': '"Arial Black", Impact, sans-serif',
    'Trebuchet MS': '"Trebuchet MS", sans-serif',
    'Verdana': 'Verdana, sans-serif',
    'Papyrus': 'Papyrus, fantasy',
  };
  IM.fontStack = (name) => FONT_STACKS[name] || ('"' + name + '", "Helvetica Neue", Helvetica, Arial, sans-serif');
})(window.IM = window.IM || {});
